export type IBank = "default"
    | "mile"
    | "sepah"
    | "post_bank"
    | "tosee_saderat"
    | "sanaat_o_maadan"
    | "keshavarzi"
    | "maskan"
    | "toose_taavon"
    | "eghtesad_novin"
    | "parsian"
    | "karafarin"
    | "saman"
    | "pasargad"
    | "arman"
    | "noor"
    | "melal"
    | "kosar"
    | "tosee"
    | "resalat"
    | "mehr_iran"
    | "mehr"
    | "mehr"
    | "ayande"
    | "khavarmianeh"
    | "ghavamin"
    | "iran_zamin"
    | "gardeshgari"
    | "hekmat"
    | "sarmaye"
    | "sina"
    | "shahr"
    | "dey"
    | "ansar"
    | "tejarat"
    | "refah"
    | "saderat"
    | "mellat"
    ;

export default function (name: IBank) {
    switch (name) {
        case "mile":
            return require("../../../../../assets/bank/bank_ic_1.png");
        case "sepah":
            return require("../../../../../assets/bank/bank_ic_2.png");
        case "post_bank":
            return require("../../../../../assets/bank/bank_ic_3.png");
        case "tosee_saderat":
            return require("../../../../../assets/bank/bank_ic_4.png");
        case "sanaat_o_maadan":
            return require("../../../../../assets/bank/bank_ic_5.png");
        case "keshavarzi":
            return require("../../../../../assets/bank/bank_ic_6.png");
        case "maskan":
            return require("../../../../../assets/bank/bank_ic_7.png");
        case "toose_taavon":
            return require("../../../../../assets/bank/bank_ic_8.png");
        case "eghtesad_novin":
            return require("../../../../../assets/bank/bank_ic_9.png");
        case "parsian":
            return require("../../../../../assets/bank/bank_ic_10.png");
        case "karafarin":
            return require("../../../../../assets/bank/bank_ic_11.png");
        case "saman":
            return require("../../../../../assets/bank/bank_ic_12.png");
        case "pasargad":
            return require("../../../../../assets/bank/bank_ic_13.png");
        case "sarmaye":
            return require("../../../../../assets/bank/bank_ic_14.png");
        case "sina":
            return require("../../../../../assets/bank/bank_ic_15.png");
        case "shahr":
            return require("../../../../../assets/bank/bank_ic_16.png");
        case "dey":
            return require("../../../../../assets/bank/bank_ic_17.png");
        case "ansar":
            return require("../../../../../assets/bank/bank_ic_18.png");
        case "tejarat":
            return require("../../../../../assets/bank/bank_ic_19.png");
        case "refah":
            return require("../../../../../assets/bank/bank_ic_20.png");
        case "saderat":
            return require("../../../../../assets/bank/bank_ic_21.png");
        case "mellat":
            return require("../../../../../assets/bank/bank_ic_22.png");
        case "hekmat":
            return require("../../../../../assets/bank/bank_ic_23.png");
        case "gardeshgari":
            return require("../../../../../assets/bank/bank_ic_24.png");
        case "iran_zamin":
            return require("../../../../../assets/bank/bank_ic_25.png");
        case "ghavamin":
            return require("../../../../../assets/bank/bank_ic_26.png");
        case "khavarmianeh":
            return require("../../../../../assets/bank/bank_ic_27.png");
        case "ayande":
            return require("../../../../../assets/bank/bank_ic_28.png");
        case "mehr":
            return require("../../../../../assets/bank/bank_ic_29.png");
        case "mehr_iran":
            return require("../../../../../assets/bank/bank_ic_30.png");
        case "resalat":
            return require("../../../../../assets/bank/bank_ic_31.png");
        case "tosee":
            return require("../../../../../assets/bank/bank_ic_32.png");
        case "kosar":
            return require("../../../../../assets/bank/bank_ic_33.png");
        case "melal":
            return require("../../../../../assets/bank/bank_ic_34.png");
        case "noor":
            return require("../../../../../assets/bank/bank_ic_35.png");
        case "arman":
            return require("../../../../../assets/bank/bank_ic_36.png");
        default:
            return require("../../../../../assets/bank/bank_ic.png");
    }
}