export const primary = {
    primaryLight: "#CFD8DC",
    primary: "#607D8B",
    primaryDark: "#37474F",
    info: "#3F57D3",
    success: "#5cb85c",
    danger: "#d9534f",
    warning: "#f0ad4e",
    darkLight: "#222",
    dark: "#000",
    white: "#fff",
    disabled: "#b5b5b5",
    disabledLight: "#f1f1f1",
    border: "#D9D5DC",
    float: "left",
    size: {
        xxSmall: 8,
        xSmall: 12,
        small: 14,
        mid: 16,
        large: 18,
        xLarge: 22,
        xxLarge: 28,
    },
    unit: 2,
};
export const secondary = {
    primaryLight: "#00BCD4",
    primary: "#00BCD4",
    primaryDark: "#00ACC1",
    info: "#3F57D3",
    success: "#5cb85c",
    danger: "#d9534f",
    warning: "#f0ad4e",
    darkLight: "#222",
    dark: "#000",
    white: "#fff",
    disabled: "#b5b5b5",
    disabledLight: "#f1f1f1",
    border: "#D9D5DC",
    float: "left",
    size: {
        xxSmall: 8,
        xSmall: 10,
        small: 12,
        mid: 16,
        large: 20,
        xLarge: 26,
        xxLarge: 32,
    },
    unit: 2,
};
export const light = {
    primaryLight: "#CFD8DC",
    primary: "#607D8B",
    primaryDark: "#37474F",
    info: "#3F57D3",
    success: "#5cb85c",
    danger: "#d9534f",
    warning: "#f0ad4e",
    darkLight: "#222",
    dark: "#000",
    white: "#fff",
    disabled: "#b5b5b5",
    disabledLight: "#f1f1f1",
    border: "#D9D5DC",
    float: "left",
    size: {
        xxSmall: 8,
        xSmall: 10,
        small: 12,
        mid: 16,
        large: 20,
        xLarge: 26,
        xxLarge: 32,
    },
    unit: 2,
};
export const dark = {
    primaryLight: "#CFD8DC",
    primary: "#607D8B",
    primaryDark: "#37474F",
    info: "#3F57D3",
    success: "#5cb85c",
    danger: "#d9534f",
    warning: "#f0ad4e",
    darkLight: "#222",
    dark: "#000",
    white: "#fff",
    disabled: "#b5b5b5",
    disabledLight: "#f1f1f1",
    border: "#D9D5DC",
    float: "left",
    size: {
        xxSmall: 8,
        xSmall: 10,
        small: 12,
        mid: 16,
        large: 20,
        xLarge: 26,
        xxLarge: 32,
    },
    unit: 2,
};